describe('My First Test', () => {
    it('Visits to page', () => {
      cy.visit('http://192.168.0.122:11080/')
        cy.contains('Sign in')
        cy.wait(1000)

      

// for sign in page testing
cy.get('#username').type("admin@ipss.crm.techgenzi")
cy.wait(1000)
cy.get('#password').type("Ipss@Admin")
cy.wait(1000)
cy.get('#username').clear()
cy.wait(1000)
cy.get('#password').clear()
cy.wait(1000)
cy.get('#submit').click()
cy.wait(1000)
cy.get('#username').type("admin@ipss.crm.techgenzi.com")
cy.wait(1000)
cy.get('#password').type("Ipss@Admin")
cy.wait(1000)
cy.get('#submit').click()
cy.wait(1000)

// for customer type
cy.get('#LT').click()
cy.wait(1000)
cy.contains('Customer Type')
cy.contains('Description')
cy.wait(1000)
cy.get('#add').click()
cy.wait(1000)
cy.get('#cancel').click()
cy.wait(1000)
cy.get('#add').click()
cy.wait(1000)
cy.get('#customer_type').type("New Customer")
cy.wait(1000)
cy.get('#cust_type_description').type("New Customer Description")
cy.wait(1000)
cy.get('#submit').click()
cy.wait(1000)
cy.get('#customer_type').clear()
cy.wait(1000)
cy.get('#customer_type').type("Moderate customer")
cy.wait(1000)
cy.get('#submit').click()
cy.wait(3000)
cy.contains('Moderate customer').click()
cy.wait(1000)
cy.get('#edit').click()
cy.wait(1000)
cy.get('#customer_type').clear()
cy.wait(1000)
cy.get('#customer_type').type("Moderate")
cy.wait(1000)
cy.get('#submit').click()
cy.wait(3000)
cy.contains('Moderate').click()
cy.wait(1000)
cy.get('#delete').click()
cy.wait(1000)
// for upload
// cy.get('#upload').click()
// cy.wait(1000)
// cy.get('#csvFileInput').click()
cy.get('#download').click()


})
})
