name: Attendance Configuration Build and Push

on:
  push:
    branches:
      - hrm/develop
    paths: 
      - Ot_Config/**


jobs:
  container_build:
    uses: ./.github/workflows/react-ab-prod-build.yml
    secrets: inherit
    with:
      react-folder: 'Ot_Config'
      mfp-folder: 'attendance_configuration'
