name: Auth Build and Push

on:
  push:
    branches:
      - hrm/develop
    paths: 
      - Auth/**


jobs:
  container_build:
    uses: ./.github/workflows/react-ab-prod-build.yml
    secrets: inherit
    with:
      react-folder: 'Auth'
      mfp-folder: 'auth'
