name: Employerconfig Build and Push

on:
  push:
    branches:
      - develop
    paths: 
      - Employerconfig/**


jobs:
  container_build:
    uses: ./.github/workflows/react-dev-build.yml
    secrets: inherit
    with:
      react-folder: 'Employerconfig'
      mfp-folder: 'employerconfig'
                   