name: Incentive Provide Build and Push

on:
  push:
    branches:
      - hrm/pmt-build
    paths:
      - IncentiveProvide/**

jobs:
  container_build:
    uses: ./.github/workflows/react-pmt-build.yml
    secrets: inherit
    with:
      react-folder: "IncentiveProvide"
      mfp-folder: "incentive_provide"
