name: Mapping Build and Push

on:
  push:
    branches:
      - hrm/pmt-build
    paths:
      - Mapping/**

jobs:
  container_build:
    uses: ./.github/workflows/react-pmt-build.yml
    secrets: inherit
    with:
      react-folder: "Mapping"
      mfp-folder: "mapping"
