name: Supportticket Build and Push

on:
  push:
    branches:
      - develop
    paths: 
      - Supportticket/**


jobs:
  container_build:
    uses: ./.github/workflows/react-dev-build.yml
    secrets: inherit
    with:
      react-folder: 'Supportticket'
      mfp-folder: 'supportticket'
                   