name: Teamassign Build and Push

on:
  push:
    branches:
      - hrm/pmt-build
    paths:
      - teamassign/**

jobs:
  container_build:
    uses: ./.github/workflows/react-pmt-build.yml
    secrets: inherit
    with:
      react-folder: "teamassign"
      mfp-folder: "teamassign"
