name: Userroles Build and Push

on:
  push:
    branches:
     - hrm/develop

    paths: 
      - user_roles/**


jobs:
  container_build:
    uses: ./.github/workflows/react-ab-prod-build.yml
    secrets: inherit
    with:
      react-folder: 'user_roles'
      mfp-folder: 'user_roles'
                   